import os
from dotenv import load_dotenv
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_ollama.embeddings import OllamaEmbeddings
# from langchain_mistralai import ChatMistralAI
from langchain_ollama.chat_models import ChatOllama
from mongoDB_storage import save_message, get_all_messages
from langchain.agents import create_agent
from langchain.agents.middleware import SummarizationMiddleware

load_dotenv()

MISTRAL_NEMO = os.getenv("MISTRAL_NEMO")
OLLAMA_MODEL = os.getenv("OLLAMA_LATEST")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL")
BASE_URL=os.getenv("BASE_URL")

def main ():
    """
    This is the main function
    """
    global all_data
    global messages
    try:

        try:
            file_path = ["company_policies.pdf","faq.pdf","product_manual.pdf"]
            all_data=[]

            for path in file_path:
                loader = PyPDFLoader(path)
                docs = loader.load()
                document = [doc.page_content for doc in docs]
                print(document)

                splitter = RecursiveCharacterTextSplitter(chunk_size=600, chunk_overlap=175)
                split_text = splitter.split_text(document)

                all_data.extend(split_text)

        except Exception as e:
            print(f"Error while splitting-text: {e}")

        try:
            embedder = OllamaEmbeddings(model=EMBEDDING_MODEL)

            if os.path.exists('./chroma_db'):
                vector_store = Chroma(
                    embedding_function=embedder,
                    persist_directory="chroma_db")
            else:
                vector_store = Chroma.from_documents(
                                        all_data,
                                        embedder,
                                        persist_directory="chroma_db")
                vector_store.persist()

            retriever = vector_store.as_retriever(
                                    search_type='mmr',
                                    search_kwargs= {
                                        'k' : 2,
                                        'fetch_k' : 10,
                                        'lambda_mat' : 0.75
                                    }
                                )
        except Exception as e:
            print(f"Error while Storing in Chroma : {e}")

        system_prompt = """
                        ## You are a helpful RAG Chatbot.
                        
                        #  Before giving any answer make sure you check the query carefully.
                        #  Do not hallucinate make sure to answer from the provided context.
                        #  If you don't know something say I Don't know.
                        """

        llm = ChatOllama(
            model=MISTRAL_NEMO,
            temperature=0.25,
            base_url=BASE_URL,
        )

        agent = create_agent(
                        model=llm,
                        system_prompt=system_prompt,
                        middleware=[
                            SummarizationMiddleware(
                                model=llm,
                                trigger=('messages',6),
                                keep=('messages',6)
                            )
                        ]

                    )

        session_id = "user_1"
        messages = []

        try:
            while True:
                print("\n\n #### --- Welcome to CHATBOT --- #### \n\n")
                query = input("You: Enter your Query (Type exit to close): \n")

                if query.lower() == "exit":
                    break

                user_input = """
                             Answer the Question from the following context below:
                             context
                             {context}
                             
                             question
                             {question}
                             """

                messages = {'role':'user','content': user_input}
                config = {'configurable' : {'thread_id':"1"}}

                result = agent.invoke({
                                "messages": messages
                            }, config=config)

                print(f"Result : {result["messages"][-1].content}")

                save_message(session_id,'user',query)  # saving user query
                save_message(session_id,'AI',result)   # saving result generated by the AI

                messages = result['messages']

            hist = get_all_messages(session_id)
            print(hist)

        except Exception as e:
            print(f"Error in while-loop: {e}")

    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()
